### ISSUE TITLE
Failes when trying to parse .doc on Linux

### ISSUE THREAD

**Issue by andre0799** [dbashford/textract#100]
I get this error when trying to parse a .doc file on my application on Heroku (Linux), so it uses antiword

`Error: file named [[ textract_file_23063383517 ]] does not appear to really be a .doc file`

But I can read it just fine on my OSX machine with textutil
I used this https://github.com/bricel/heroku-buildpack-antiword to install antiword on Heroku

**Comment by dbashford** [comment]
Closing this in favor of #94 which I believe is the same root issue.
