### ISSUE TITLE
Uncaught TypeError: fs.existsSync is not a function(…) 

### ISSUE THREAD

**Issue by oliversauter** [dbashford/textract#103]
Hey folks,

thanks for your awesome work. I was looking for something like that for ages. 
Works like a charm, when using in command line. Thats where I tested its capabilities.

Now i tried to make it run in my chrome extension using browserify and npm 3.10.8.
There it throws multiple errors all surrounding the fs.exists functions. 

Any idea how I could resolve this issue?

Thanks! :)

**Comment by dbashford** [comment]
Sorry, no idea there. Likely that isn't supported in whatever environment you are porting it to? Regardless, it clearly is a node function. 

Going to close this out. Conversation can keep taking place here if need be, but it is very unlikely this is a textract issue.
