### ISSUE TITLE
Tesseract parameter passing

### ISSUE THREAD

**Issue by SebastianSingle99** [dbashford/textract#105]
How can i use tesseract parameters like `-psm 0`?
I use this method 
`textract.fromFileWithPath(filePath, {tesseract: { lang:"chi_sim", psm: 0 } }`

Textract only recognizes the 'lang' options. Looking at the source file images.js
it seems only the language options is regarded.

`if ( options.tesseract && options.tesseract.lang ) {
    cmd += ' -l ' + options.tesseract.lang;
 }`

Am I missing something or is this a bug?

**Comment by dbashford** [comment]
Fixed and published as `2.1`
