### ISSUE TITLE
images.js extractor testForBinary failure

### ISSUE THREAD

**Issue by OlivierB-OB** [dbashford/textract#116]
Hello,

In the function testForBinary of the images.js extractor, the idea is to run the tesseract command without providing any argument, and check if the tesseract help is displayed.

Here is the current check:

`
( error && error.toString().indexOf( 'Usage:' ) > -1 ) ||
( stderr && stderr.toString().indexOf( 'Usage:' ) > -1 )
`

The thing is the help is returned in stdout in my case (windows?).

The check shoud be:

`
( error && error.toString().indexOf( 'Usage:' ) > -1 ) ||
( stdout && stdout.toString().indexOf( 'Usage:' ) > -1 ) ||
( stderr && stderr.toString().indexOf( 'Usage:' ) > -1 )
`

Could you apply the required changes, please?
Thanks in advance!

**Comment by dbashford** [comment]
Closing this out as your PR fixed it.
