### ISSUE TITLE
Extracted text Post processing. 

### ISSUE THREAD

**Issue by shishirrawat** [dbashford/textract#121]
From the onset I would like to point out that I am new to Jquery and this question may be something that is basic knowledge. 

I am using the code to extract text from a  file. Below is my code  the docx contains "THIS IS EXTRACT"
var = "smeString";

console.log("BEFORE FUNCT");
textract.fromFileWithPath('docfile.docx', function( error, text ) {
text = text;
console.log(smeString);
});

console.log("AFTER FUNCT");
console.log(smeString);
console.log("its the END");

the OUTPUT for this is  :: 
**BEFORE FUNCT
AFTER FUNCT
a
its the END
THIS IS EXTRACT**

Why is the extracted text coming at the last. secondly is there a way to store the extracted text into a variable for further processing. maybe like 

smeString = textract.fromFileWithPath('docfile.docx', function( error, text ) {}

**Comment by thiagorova** [comment]
textract is asynchronous. if you want to use the text, you can:
   use plain old (and mighty trustworthy) javascript callbacks (which is what you have anyway => 
text = text; and console.log(smeString); are inside textract callback)
   use ECMA6 Promises around textract
   use ECMA6 asnc await

PS: i didn't see any Jquery in your code. this is all plain and wonderful Javascript

**Comment by shishirrawat** [comment]
That went right by..  Sorry I have just started out to build my idea and I don't know much of Js.. :(

Thanks for the info I will try and understand these ECMA6
