### ISSUE TITLE
when testing on runkit get an error same when trying to do on my server

### ISSUE THREAD

**Issue by thesquaremedia** [dbashford/textract#125]
Error for type: [[ image/png ]], file: [[ /tmp/6282815959.png ]], extractor for type exists, but failed to initialize. Message: INFO: 'tesseract' does not appear to be installed, so textract will be unable to extract images.

tried npm install tesseract but it wont install. looks like that package is outdated

**Comment by reviewher** [comment]
@thesquaremedia did you try `npm install -g tesseract`?

**Comment by thesquaremedia** [comment]
No I will try that thanks

**Comment by thesquaremedia** [comment]
i tried still failed with this message

` tesseract@0.0.3 install /home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/tesseract
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/tesseract/build'
  CXX(target) Release/obj.target/tesseract_bindings/src/tesseract_bindings.o
../src/tesseract_bindings.cc:7:0: warning: "BUILDING_NODE_EXTENSION" redefined [enabled by default]
 #define BUILDING_NODE_EXTENSION
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from ../src/tesseract_bindings.cc:9:0:
../src/tesseract_baseapi.h:10:21: fatal error: baseapi.h: No such file or directory
 #include <baseapi.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/tesseract_bindings/src/tesseract_bindings.o] Error 1
make: Leaving directory `/home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/tesseract/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.17-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v6.11.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.nvm/versions/node/v6.11.1/lib/node_modules/tesseract
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.1/bin/npm" "install" "-g" "tesseract"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tesseract@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tesseract@0.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tesseract package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tesseract
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tesseract
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log`

**Comment by dbashford** [comment]
Check the [Extraction Requirements](https://github.com/dbashford/textract#extraction-requirements) in the documentation, it provides a link to the project on github. tesseract isn't a functioning NPM package, so textract relies on you having installed the binary.

https://github.com/tesseract-ocr/tesseract/wiki

Going to close this, if that doesn't work for you keep updating this ticket, if I can determine there is some sort of issue textract I will reopen.
