### ISSUE TITLE
Installing pdftotext

### ISSUE THREAD

**Issue by dylankbuckley** [dbashford/textract#126]
Very basic issue. How do I install pdftotext into my node project so that I stop getting this:

`Message: INFO: 'pdftotext' does not appear to be installed, so textract will be unable to extract PDFs.`

**Comment by reviewher** [comment]
@dylankbuckley you can grab the pre-compiled `pdftotext` tool from http://www.xpdfreader.com/download.html -- get the "Xpdf tools"

**Comment by dylankbuckley** [comment]
@reviewher Thanks and where do I put into my project so that it has access to it?

**Comment by reviewher** [comment]
The test expects the pdftotext tool to be in PATH.  You can put it in a system-wide location like `/usr/local/bin`.  If you don't want to install it, and you are requiring the `textract` module, add the directory to your path by appending to process.env.PATH

**Comment by dbashford** [comment]
Anticipating the help given above should do the trick. =) Thanks for jumping in @reviewher!

**Comment by nrsharma11** [comment]
Thanks. I have downloaded the tool and paste the exe in windows folder. It's working now.
