### ISSUE TITLE
How to pass option as rejectUnauthorized:false in node textract

### ISSUE THREAD

**Issue by iyyappanpauls** [dbashford/textract#129]
How to pass option as rejectUnauthorized:false in node textract, I tried many way its not working, pls help me asap.

**Comment by iyyappanpauls** [comment]
How to pass option as rejectUnauthorized:false in node textract, I tried many way its not working, pls help me asap.

**Comment by dbashford** [comment]
To what end? What is it you are trying to do?

**Comment by dbashford** [comment]
Closing due to lack of feedback. If I can get more details, I can reopen.
