### ISSUE TITLE
is Not a word document error antiword

### ISSUE THREAD

**Issue by Hari-Guhan-s** [dbashford/textract#132]
I have installed Antiword in ubuntu and tried to parse a .doc file but Antiword shows "is not a Word 
Document",  But i am sure that the mime type of the file is application/msword,can anyone please help me out.

**Comment by dbashford** [comment]
This is something you've done with Antiword directly? Not with textract?

**Comment by Hari-Guhan-s** [comment]
no i have tried this trough textract process call in python

**Comment by dbashford** [comment]
You sure you are using this node package and not the [python textract](https://github.com/deanmalmgren/textract) which also uses Antiword?

**Comment by luishenriquesb** [comment]
Guys, any solution for this issue? I'm dealing the same problem with that file  
[test1.doc.tar.gz](https://github.com/dbashford/textract/files/4792666/test1.doc.tar.gz)
