### ISSUE TITLE
return an error when reading .rtf file

### ISSUE THREAD

**Issue by HenryYong** [dbashford/textract#135]
Hi, I am using textract to read a .rtf file, the content of that file is Chinese. When I ran my code, I got following feedback in Terminal:
![image](https://user-images.githubusercontent.com/7967105/34167430-bee0215e-e51c-11e7-9ba0-13bf91161101.png)
But later, my code can still work and get what I want...

and my code is very simple like this:
![image](https://user-images.githubusercontent.com/7967105/34167539-fe9e04f0-e51c-11e7-8da0-ae39406b35c0.png)

**Comment by dbashford** [comment]
So everything is working, and you get what you want, but you are getting an error to the console?

Do you have an example file I can use?

**Comment by dbashford** [comment]
Closing this due to lack of feedback. If you have feedback to provide, let me know and I can reopen, but without more details I'll struggle to figure out what this is about.
