### ISSUE TITLE
Get Error while using this module in Angular 5 project.

### ISSUE THREAD

**Issue by Vigor111** [dbashford/textract#136]
These are what I have got.
> WARNING in ./node_modules/textract/lib/extract.js
> 84:11-39 Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/textract/lib/extract.js
>  @ ./node_modules/textract/lib/index.js
>  @ ./src/app/app.component.ts
>  @ ./src/app/app.module.ts
>  @ ./src/main.ts
>  @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts
> 
> ERROR in ./node_modules/textract/lib/util.js
> Module not found: Error: Can't resolve 'child_process' in '/Volumes/Work/SourceTree/ChromeExtension/node_modules/textract/lib'
>  @ ./node_modules/textract/lib/util.js 1:11-37
>  @ ./node_modules/textract/lib/extract.js
>  @ ./node_modules/textract/lib/index.js
>  @ ./src/app/app.component.ts
>  @ ./src/app/app.module.ts
>  @ ./src/main.ts
>  @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by dbashford** [comment]
Can't resolve `'child_process'`? 

Angular is a web framework. This is a node project. I wouldn't expect this to work on the web. The fact that `child_process` (a node library) isn't a thing would lead me to believe there are environmental concerns outside of textract's control that are keeping it from running.

**Comment by Vigor111** [comment]
I must use `textract` in my project, so what can I do?

**Comment by dbashford** [comment]
You cannot use it on the web. Nothing I can do about that. It isn't a web library any more than some Ruby code is a web library.

You'd need a node backend to your webapp to do the work for you.
