### ISSUE TITLE
Extracting alt text from HTML?

### ISSUE THREAD

**Issue by matatk** [dbashford/textract#137]
I've just been recommended textract and it looks very cool; thanks. I am trying to extract text from HTML and it works fine with things like

```html
<div id="blah">Some Text</div>
```

but it doesn't pick up `alt` text, such as

```html
<img src="..." alt="A text alternative for this image">
```

I was wondering if you have any plans for such a feature (or, if I've missed it, how to extract the values of attributes like this)?

**Comment by dbashford** [comment]
You haven't missed it, and no plans, but no reason it can't be introduced as a feature!

**Comment by matatk** [comment]
Hi, just got the closure notice for this issue; can see you have been working on it; thanks. I have been working on it too, and [created a small library to extract `alt` and various other user-facing text attributes from HTML](https://github.com/matatk/html-text-extract)—I have been testing it for a while, which is why I didn't mention it here, though I probably should've, oops.

If you'd like to use the code I wrote for extracting not just `alt`s but other user-facing text from HTML, then feel free (I can help with a PR too if you'd like).

**Comment by dbashford** [comment]
I can create another issue to track the other user-facing attributes and include them in the solution. Ought not be too hard to include most of them.
