### ISSUE TITLE
Replace pdftotext with PDF.js?

### ISSUE THREAD

**Issue by njlr** [dbashford/textract#138]
Mozilla's [PDF.js](https://github.com/mozilla/pdf.js) allows PDF text extraction using pure JavaScript. 

Perhaps `pdftotext` should be replaced by a PDF.js-based implementation?

**Comment by dbashford** [comment]
The question is how does it perform? A goal of textract is to handle extraction at scale, so runtime speed at the expense of some setup pain (dealing with pdftotext install) is OK.

**Comment by dbashford** [comment]
I will in the long term take a look at this. But it is not a priority. Will have to spike and dig into performance.

**Comment by njlr** [comment]
It might be interesting to create a peer dependency on either PDF.js OR pdftotext, and allow the user to decide. The interfaces would have to be abstracted somehow.

**Comment by markb-trustifi** [comment]
pdftotext requires installing machine-level 3rd party dendencies that are not opensource.
I vote for PDF.js

**Comment by perevernihata** [comment]
I also vote for pdf.js. Reason behind my logic is that if you bake package that is using textract on one mashine, and then publish baked package to another one you will get this error: 
```
{
    "errorMessage": "Error for type: [[ application/pdf ]], file: [[ /tmp/file.pdf ]], extractor for type exists, but failed to initialize. Message: INFO: 'pdftotext' does not appear to be installed, so textract will be unable to extract PDFs.",
    "errorType": "Error",
    "stackTrace": [
        "extract (/var/task/node_modules/textract/lib/extract.js:147:15)",
        "/var/task/node_modules/textract/lib/index.js:17:7",
        "FSReqWrap.cb [as oncomplete] (fs.js:312:19)"
    ]
}
```

**Comment by perevernihata** [comment]
Actually, I get similar error for `doc` files 😞 
```
{
    "errorMessage": "Error for type: [[ application/msword ]], file: [[ /tmp/file.doc ]], extractor for type exists, but failed to initialize. Message: INFO: 'antiword' does not appear to be installed, so textract will be unable to extract DOCs.",
    "errorType": "Error",
    "stackTrace": [
        "extract (/var/task/node_modules/textract/lib/extract.js:147:15)",
        "/var/task/node_modules/textract/lib/index.js:17:7",
        "FSReqWrap.cb [as oncomplete] (fs.js:312:19)"
    ]
}
```

**Comment by dbashford** [comment]
Closing this out as a PR has come in to do this work.
