### ISSUE TITLE
Type Error: Textract is not a function 

### ISSUE THREAD

**Issue by kittureddy123** [dbashford/textract#140]
Hi Team,
I am running the resume parser in windows platform, i am getting the following error

\code4goal-resume-parser-master\src\libs\processing.js:51
textract(file, {preserveLineBreaks: true}, function(err, data) {
^
TypeError: textract is not a function
at extractText (e:\code4goal-resume-parser-master\src\libs\processing.js:51:3)
at Object.processFile [as run] (e:\code4goal-resume-parser-master\src\libs\processing.js:15:3)
at e:\code4goal-resume-parser-master\src\ParseBoy.js:27:16
at Function..each..forEach (e:\code4goal-resume-parser-master\node_modules\underscore\underscore.js:153:9)
at ParseBoy.willHelpWithPleasure (e:\code4goal-resume-parser-master\src\ParseBoy.js:26:4)
at SomeHR. (e:\code4goal-resume-parser-master\app.js:36:14)
at e:\code4goal-resume-parser-master\src\SomeHR.js:35:21
at FSReqWrap.oncomplete (fs.js:135:15)

I have installed below version dependencies
"request": "^2.53.0",
"textract": "^2.2.0",
"underscore": "^1.8.3"

**Comment by dbashford** [comment]
Did you `require('textract')`?

**Comment by kittureddy123** [comment]
Hi dbashford ,

Yes , you can see in the following file /libs/processing.js/

var path = require('path');
var _ = require('underscore');
var textract = require('textract');
var mime = require('mime');
var fs = require('fs');

module.exports.run = processFile;

/**
 *
 * @param file
 * @param cbAfterProcessing
 */
function processFile(file, cbAfterProcessing) {
  extractText(file, function(PreparedFile) {
    console.log(file);
    if (_.isFunction(cbAfterProcessing)) {
      cbAfterProcessing(PreparedFile);
    } else {
      return console.error('cbAfterProcessing should be a function');
    }
  });
}

/**
 *
 * @param data
 * @returns {string}
 */
function cleanTextByRows(data) {
  var rows,
    clearRow,
    clearRows = [];

  rows = data.split("\n");
  for (var i = 0; i < rows.length; i++) {
    clearRow = cleanStr(rows[i]);
    if (clearRow) {
      clearRows.push(clearRow);
    }
  }

  return clearRows.join("\n") + "\n{end}";
}

/**
 *
 * @param file
 * @param cbAfterExtract
 */
function extractText(file, cbAfterExtract,) {
  textract(file, {preserveLineBreaks: true}, function(err, data) {
    if (err) {
      return console.log(err);
    }
    if (_.isFunction(cbAfterExtract)) {
      data = cleanTextByRows(data);
      var File = new PreparedFile(file, data.replace(/^\s/gm, ''));
      cbAfterExtract(File);
    } else {
      return console.error('cbAfterExtract should be a function');
    }
  });
}

/**
 *
 * @param str
 * @returns {string}
 */
function cleanStr(str) {
  return str.replace(/\r?\n|\r|\t|\n/g, '').trim();
}

function PreparedFile(file, raw) {
  this.path = file;
  this.mime = mime.lookup(file);
  this.ext = mime.extension(this.mime);
  this.raw = raw;
  this.name = path.basename(file);
}

/**
 *
 * @param Resume
 */
PreparedFile.prototype.addResume = function(Resume) {
  this.resume = Resume;
};

PreparedFile.prototype.saveResume = function(path, cbSavedResume) {
  path = path || __dirname;

  if (!_.isFunction(cbSavedResume)) {
    return console.error('cbSavedResume should be a function');
  }

  if (fs.statSync(path).isDirectory() && this.resume) {
    fs.writeFile(path + '/' + this.name + '.json', this.resume.jsoned(), cbSavedResume);
  }
};

**Comment by dbashford** [comment]
Happy to help if you can put a github repo up, but this isn't a textract problem, per se.
