### ISSUE TITLE
pdftotext lib error in aws lambda server

### ISSUE THREAD

**Issue by SreekanthMekala** [dbashford/textract#142]
Team, We are getting error when trying to extract data from pdf file.

Please help us make it work.

Error: Error for type: [[ application/pdf ]], file: [[ /tmp/uploads/4dde1d57cc1289f0d8009f4b10626c37 ]], extractor for type exists, but failed to initialize. Message: INFO: ‘pdftotext’ does not appear to be installed, so textract will be unable to extract PDFs.

Thanks in advance.

**Comment by dbashford** [comment]
Hi! Thanks for using the library!

Afraid troubleshooting that environment is well outside my expertise. But it is going to come down to two things:

1) Can `pdftotext` be installed there?
2) Is `pdftotext` available at the command line? textract effectively shells out to run `pdftotext`. If you cannot run `pdftotext` by simply typing it at the command-line from where textract runs, then textract can't access it either.

![image](https://user-images.githubusercontent.com/581127/35695054-5d86831a-0751-11e8-9ffb-7dc0018a796f.png)

**Comment by SreekanthMekala** [comment]
Thanks Team,
There is No module like pdftotext, Can you please suggest us more. We have
module pdf-to-text is it support?

--
Regards,
*Sreekanth Mekala.*

**Comment by dbashford** [comment]
What do you mean there is no module like pdftotext?

http://www.xpdfreader.com/download.html

Without pdftotext installed, textract cannot extract PDFs.

**Comment by dbashford** [comment]
Closing this. Not much I can do about missing deps.

**Comment by deepdil-sp** [comment]
what to do with this issue?

**Comment by defi-bear** [comment]
https://github.com/Shing-Ho/textract
use this one. This doesn't require pdftotext and antiword
