### ISSUE TITLE
Require extractors on demand

### ISSUE THREAD

**Issue by endling1** [dbashford/textract#143]
Hi,
Thank you for this library.

I'm using textract in an electron application.
The user provides a file, its content is extracted using textract and displayed.

It works great, but I've noticed a runtime memory increase of almost 40mb when I start using textract api's.
The reason seems to be that textract _require_'s all extractors of all file types at once.
Are there any plans to change this behavior to only _require_ extractors which are needed ?

**Comment by endling1** [comment]
Clone of #86

**Comment by dbashford** [comment]
I can look into this. As you noticed, it has been an ask in the past. The Electron use case is the first really compelling one I've heard. No promises on timeline, but I can prioritize checking this out when some time frees up.
