### ISSUE TITLE
working with password protected documents

### ISSUE THREAD

**Issue by tansaku** [dbashford/textract#146]
does anyone happen to have used textract on password protected documents, e.g. pdfs.  Is there some simple way to pass the password in via the command line, or programmatically?

**Comment by tansaku** [comment]
I'm thinking that https://www.npmjs.com/package/node-qpdf might be the solution ...

**Comment by dbashford** [comment]
Will not work now. Can take a look at this as a feature.

**Comment by dbashford** [comment]
So I "fixed" this by documenting how it already worked! My bad for not realizing it would.

If you are interested in something other than password protected PDFs, open another issue with specfics?
