### ISSUE TITLE
'duplexer2' module error.

### ISSUE THREAD

**Issue by nityanandagohain** [dbashford/textract#148]
I am a newbie.
I have just installed textract but while running I am getting "Cannot find module 'duplexer2'" error.

I have installed "duplexer2" still the same error is showing up.
![screenshot from 2018-03-16 20-32-05](https://user-images.githubusercontent.com/26831659/37528136-d36c4aa4-2959-11e8-9ba0-e113a995769b.png)
Also some more tutorials in depth will be helpful to me.

**Comment by dbashford** [comment]
I cannot duplicate this locally and it leads me to believe that something went wrong when textract was installed via NPM/Yarn. That is outside my scope of influence.

It does look like a few other folks have run into this? https://github.com/johnpapa/ng-demos/issues/59

If reinstalls do not work, post any issues you have during install? Going to close this but will check back to help if I can.
