### ISSUE TITLE
Use only Github based dependencies

### ISSUE THREAD

**Issue by markb-trustifi** [dbashford/textract#153]
Dependencies require separate installation on machine that is inconvenient and can make problems in hosted environments. Instead of them there can be used relevant opensource projects from Github.

1) XpdfReader (http://www.foolabs.com/xpdf/download.html) is not opensource, it can be replaced with project pdf.js (https://github.com/mozilla/pdf.js).
npm i pdfjs-dist --save
2) UnRTF (https://www.gnu.org/software/unrtf) project has JS version in Github - https://github.com/walling/node-unrtf.
npm i unrtf --save
3) Antiword (http://www.winfield.demon.nl) - no JS project. Can be converted to JS with 
emscripten https://github.com/kripken/emscripten
4) Tesseract (https://github.com/tesseract-ocr/tesseract) project has JS version in Github -https://github.com/naptha/tesseract.js
npm i tesseract.js --save

**Comment by dbashford** [comment]
Performance is important, more important than eliminating the inconvenience of third-party dependencies. Not sure I have time in the near-term to spike performance. But it is something I can look into in the future.

FWIW node-unrtf depends on 3rd party dependencies.

**Comment by markb-trustifi** [comment]
Thanks for the answer.
If you would like to up performance the good place is to stop saving buffers to files and after that load them back again from files to buffers.

**Comment by dbashford** [comment]
Closing this out. Worthwhile pursuing this one external dependency at a time, but not all at once.
