### ISSUE TITLE
preserveLineBreaks but only if they are in pairs?

### ISSUE THREAD

**Issue by tansaku** [dbashford/textract#156]
Apologies if this is a silly feature request, but we're working on converting some PDF and word documents.  The PDF files seem to have line breaks in the middle of sentences (where they hit the edge of the page), while the word files do not.  Both types of files have double (or paired) line breaks where there are paragraphs.  

We'd really like to preserve the paragraphs, but eliminate the single line breaks.  Would it make sense to have another option like preserveMultipleLineBreaks or something?

**Comment by tansaku** [comment]
I've managed to achieve the effect that we would like by inserting the following:

```
text = text.replace(/(^|[^\n])\n(?!\n)/g, '$1');
```
prior to the following line in extract.js

```
text = text.replace( WHITELIST_PRESERVE_LINEBREAKS, ' ' );
```

so maybe a STRIP_ONLY_SINGLE_LINEBREAKS  option to have this run before the WHITELIST_PRESERVE_LINEBREAKS operation ...

I could pop in a pull request if this made sense ...?

**Comment by dbashford** [comment]
This isn't an outrageous ask. Probably going to run through another batch of tickets soon and get `2.3` out the door, I can toss this in.
