### ISSUE TITLE
use node modules instead of external programs

### ISSUE THREAD

**Issue by bob-omb** [dbashford/textract#16]
For example:
- [pdf-text](https://npmjs.org/package/pdf-text) for PDF files
- [xlsjs](http://npm.im/xlsjs) for XLS files
- [xlsx](http://npm.im/xlsx) for XLSX/XLSM/XLSB files 

I'm sure more pure-JS parsers exist

**Comment by slowtacocar** [comment]
I know this is an old issue, but the library that pdf-text uses under the hood--[pdf2json](https://github.com/modesty/pdf2json)--seems to work great for extracting PDFs to plain text (not an array of chunks). I needed a pure-Node solution for a project I'm working on, so I already forked the repo and modified it to use this library. It's nothing fancy, but I can go ahead and submit a PR if you'd like.
