### ISSUE TITLE
Textract issue in amazon elasticbeanstalk

### ISSUE THREAD

**Issue by deepdil-sp** [dbashford/textract#163]
My project is deployed to amazon elastic beanstalk, when i try to textract i get error in log as 

>  Error: Error for type: [[ application/pdf ]], file: [[ ../resumes/96710848773.pdf ]], extractor for type exists, but failed to initialize. Message: INFO: 'pdftotext' does not appear to be installed, so textract will be unable to extract PDFs.

Please help me

**Comment by dbashford** [comment]
afraid that is outside my scope/ability to help and outside the scope of the library, but conversation can definitely continue in this ticket if anyone has thoughts/ideas.

**Comment by defi-bear** [comment]
@deepdil-sp https://github.com/Shing-Ho/textract
use this one. This doesn't require pdftotext and antiword
