### ISSUE TITLE
processing tables

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [dbashford/textract#165]
Hello,

Is it possible to process doc with a table?

### e.g.,

Column1 | Column2 | Column3
------------ | ------------- | -------------
Content 1 | Content 2 | Content 3

### for this

Column1|Column2|Column3
Content 1|Content 2|Content 3

**Comment by dbashford** [comment]
Give me an example doc and I'll tinker with it, good chance no, though.

**Comment by carvalhoviniciusluiz** [comment]
A simple document with some tables should serve, I found this on the internet [demo.docx](https://github.com/dbashford/textract/files/2237507/demo.docx)

#### example of the first table, 2 columns

ITEM|NEEDED
Books|1
Pens|3
Pencils|2
Highlighter|2 colors
Scissors|1 pair

Managing to process it will be excellent!

**Comment by dbashford** [comment]
Going to have to say this is outside the scope of textract. Tinkered with it a little bit. To support this across all the extract types would be a huge undertaking (and another optional output like line breaks) and when the goal is text extraction and not pretty representation, not sure it is worth it.

Sorry!
