### ISSUE TITLE
Error trying to read larger files

### ISSUE THREAD

**Issue by lic001rabby** [dbashford/textract#168]
Trying to implement in a NodeJS project on Ubuntu 16.04 [Vagrant Box]
Works fine for smaller .doc files, errors with larger ones.

The error:
`antiword read of file named [[ 82b86b8e23cdd035caaa69b1f14e5555 ]] failed: Error: stdout maxBuffer exceeded
    at /vagrant/node_modules/textract/lib/extractors/doc.js:20:17
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`

Sample file https://www.sample-videos.com/doc/Sample-doc-file-1000kb.doc

Any ideas?

**Comment by dbashford** [comment]
Do a quick [scan of the docs for `maxBuffer`](https://github.com/dbashford/textract#configuration), that should fix you up.

Closing this out for now, but if there's still an issue, you are welcome to open this back up.
