### ISSUE TITLE
AWS S3 bucket file gives does not exist erro

### ISSUE THREAD

**Issue by rrrepos** [dbashford/textract#178]
I am trying to use textract to access a file from an external source. I must mention that I successfully have been able to access a file (ppt, in my case) from my local server and it generates the required text. Thanks for this wonderful library.

However, when accessing from an S3 bucket I received a does not exist error. When I use the same url on my browser, it downloads the file. I have set CORS permissions on AWS bucket. The error I get is:

`Error: File at path [[ https://s3.ap-south-1.amazonaws.com/... ]] does not exist.`

**Comment by rrrepos** [comment]
Further, I tried accessing the file using `request` and it returns status code of 200

**Comment by rrrepos** [comment]
oops. How could I miss the `textract.fromUrl`. Must read the Readme better.

**Comment by nayoung0** [comment]
how could you use textract.fromUrl?
whenever i try to use textract.fromUrl, i always get null text.
Actually, it returns text on local, but it doesn't work on server.

**Comment by rrrepos** [comment]
The following was my function in NodeJS

```
exports.annotate = function(req, res, next) {
  let filePath  = req.body.url.trim();
  textract.fromUrl(filePath, function( err, text ) {
    if (err)
      return res.status(401).json({
        status: 'error',
        data: null,
        error: err
      });
      console.log(text);
      // use the text as desired
     // in my project added it to elasticsearch to perform a full text search
      ...
  });
}
```

**Comment by rrrepos** [comment]
The only thing I can think of is whether the URL is invalid. But then, I would think it should throw an err

**Comment by nayoung0** [comment]
Thank you for your replying!
and it was my mistake.
it works now. the problem was the test code.
Thank you :)
