### ISSUE TITLE
Regular Expression Denial of Service in marked dependency

### ISSUE THREAD

**Issue by madnight** [dbashford/textract#190]
![image](https://user-images.githubusercontent.com/10064471/57864669-9bbf9a00-77fc-11e9-8bc1-8c9ca3bfc7bc.png)

**Comment by giorgio-zamparelli** [comment]
There is already a Pull Request to fix this:
https://github.com/dbashford/textract/pull/188
Can some maintainer merge and release this please?

**Comment by dbashford** [comment]
2.5.0 released, thanks for the nudge!

**Comment by giorgio-zamparelli** [comment]
Thank you @dbashford ! Just upgraded to 2.5.0 and everything works fine and npm audit vulnerabilities found went to 0.

**Comment by ram-you** [comment]
Please update marked 
![image](https://user-images.githubusercontent.com/3125972/62360178-28cae300-b510-11e9-8c4b-05bb3c4237ec.png)
