### ISSUE TITLE
Support for Buffer objects containing a base64 encoded string?

### ISSUE THREAD

**Issue by FraserThompson** [dbashford/textract#40]
Use case: An Express API for taking DOC/PDF/DOCX and returning text.

Rather than uploading a file to the server and then having textract read that off the disk it would be preferable to take a base64 encoded DOC/PDF/DOCX file sent as a string in a POST request, put it in a buffer, and then have textract read that buffer.

**Comment by dbashford** [comment]
Working this now.  As an FYI, textract still needs to write it to disk, but since it is uniquely textracts requirement that it be on disk, no reason why textract can't manage that for you.
