### ISSUE TITLE
Support for more file formats

### ISSUE THREAD

**Issue by rodrigogalindez** [dbashford/textract#42]
Hi David, 

Do you have plans to update textract to support .ppt, .~~xlsx~~, .~~xltx~~, .~~potx~~, .key, .pages, ~~.xml~~? I'd also love to see support for OpenOffice file formats, like ~~.odt~~, ~~.ott~~, ~~.ods~~, ~~.ots~~, ~~.odg~~, ~~.otg~~, ~~.odp~~, ~~.otp~~. 

Thanks!

**Comment by dbashford** [comment]
`xml`, `xlsx`, `ods` and `odt` are in the v1 branch, along with a `fromUrl` feature.

Some of the od* ones are a bit rough.  `ppt` is super hard, there is a ticket for it now. #24

I'd need to look at some of the outliers.  Some may already be supported, its just a matter of adding the mime type to an existing extractor.

**Comment by dbashford** [comment]
`key` and `pages` don't have much existing node support.  would need to figure out a ton of XML spec stuff for both formats.

**Comment by rodrigogalindez** [comment]
Perfect, thanks!

**Comment by dbashford** [comment]
Going to look into `odg/otg` and `odp/otp` later this evening.  My hope is, if they are anything like docs and sheets that they won't be too hard to knock out.

`key`, `pages` and `ppt` will have to wait.

The rest are done.

Only other thing I want to get in before I release 1.0 is some speech to text stuff via Google's API.

**Comment by dbashford** [comment]
Added new ticket to cover key and pages.  There is one for ppt.  Rest are included in v1 branch.

**Comment by rodrigogalindez** [comment]
Perfect, thanks.
