### ISSUE TITLE
Unable to extract text from doc and docx files

### ISSUE THREAD

**Issue by nishvs** [dbashford/textract#48]
Whenever i run the project i keep getting the following warnings:

textract: 'unzip' does not appear to be installed, so textract will be unable to
 extract DOCXs.
textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.

I have properly installed catdoc command and its working in command prompt using path envionment variables.

Also i am unable to install the unzip module as there is no link provided for this and i would like to know how to install it.

If anybody would provide some information on this i will be very thankful to him.

**Comment by dbashford** [comment]
What version of textract are you using?

**Comment by nishvs** [comment]
0.20.0....I got it from npm

**Comment by dbashford** [comment]
Bump to 1.0 and you won't need unzip.

If you have catdoc installed then it's installed such that textract can't use it.  Give me a few and I'll whip a script up that should help figure the issue out.

**Comment by nishvs** [comment]
Yes i just saw it my mistake....Thanks for the help david...appreciated

**Comment by dbashford** [comment]
All is good then?

**Comment by nishvs** [comment]
Yeah i am able to read text from pdf and docx file. But still when i

textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.

and at runtime i get the error

{ [Error: textract does not currently extract files of type [[ application/mswor
d ]]] typeNotFound: true }

Note: I am using catdoc which is ported for windows
http://blog.brush.co.nz/2009/09/catdoc-windows/

The reason i am using this is because on the site they say they dont support windows.

**Comment by dbashford** [comment]
Create a file, call it `doc`, and copy this text into it.  Then run it from the command line.  What does it say?

```javascript
#!/usr/bin/env node
var exec = require("child_process").exec;
exec('catdoc ' + __filename,
  function (error, stdout, stderr) {
    if (error) {
      console.log("catdoc cannot be found/executed by this script, errors to follow.")
      console.log("**************ERROR*****************");
      console.log(error);
      console.log("**************stderr*****************")
      console.log(stderr);
      console.log("**************stdout*****************")
      console.log(stdout);
    } else {
      console.log("Found catdoc, textract should be able to use it.")
    }
  }
);
```

**Comment by nishvs** [comment]
I pasted the code in a method and called the method in the application.
I am using windows environment.

catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc E:\NewStartu
p\Code\Tutorial\Node Samples\SampleNodeProject\ClientApp\controllers\home.js"
catdoc: No such file or directory
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc E:\\NewStartup\\Code\\Tutor
ial\\Node Samples\\SampleNodeProject\\ClientApp\\controllers\\home.js"' }
**************stderr*****************
catdoc: No such file or directory
catdoc: No such file or directory

**************stdout*****************

{ [Error: textract does not currently extract files of type [[ application/mswor
d ]]] typeNotFound: true }
catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc E:\NewStartu
p\Code\Tutorial\Node Samples\SampleNodeProject\ClientApp\controllers\home.js"
catdoc: No such file or directory
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc E:\\NewStartup\\Code\\Tutor
ial\\Node Samples\\SampleNodeProject\\ClientApp\\controllers\\home.js"' }
**************stderr*****************
catdoc: No such file or directory
catdoc: No such file or directory

**************stdout*****************

**Comment by nishvs** [comment]
I think the input file is not provided.

**Comment by dbashford** [comment]
That script is just trying to `catdoc` itself.  Is `home.js` where you put the text I put above?

**Comment by nishvs** [comment]
yes in home.js i have put the script in a method which i called.

**Comment by nishvs** [comment]
I got this output when i gave the correct input file path.

Found catdoc, textract should be able to use it.

**Comment by dbashford** [comment]
How is it getting the path wrong?

**Comment by dbashford** [comment]
I don't have a Windows machine to test on I'm afraid, so I may need your help to debug this really quickly.

If you find go into `node_modules/textract/lib/extractors/doc.js` and add those `console.log`s from above to this line: https://github.com/dbashford/textract/blob/master/lib/extractors/doc.js#L49

That'll help me figure out what might be happening.

**Comment by nishvs** [comment]
This is the change which i did to ur script. I remode __filename and added "./Resume.doc after catdoc 

var exec = require("child_process").exec;
// exec('catdoc ' + __filename,
exec('catdoc ./Resume.doc' ,
function (error, stdout, stderr) {
  if (error) {
    console.log("catdoc cannot be found/executed by this script, errors to follow.")
    console.log("**************ERROR*****************");
    console.log(error);
    console.log("**************stderr*****************")
    console.log(stderr);
    console.log("**************stdout*****************")
    console.log(stdout);
  } else {
    console.log("Found catdoc, textract should be able to use it.")
  }
}
);

**Comment by dbashford** [comment]
I wonder if it has an issue with the file not being a `.doc` and its just giving a very bad error.

If you change the path again and point it at the script itself the way you pointed at `Resume.doc` what happens?

**Comment by nishvs** [comment]
textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.
textract: 'drawingtotext' does not appear to be installed, so it will be unable
to extract DXFs.
catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc ../controlle
rs/home.js"
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc ../controllers/home.js"' }
**************stderr*****************
catdoc: No such file or directory

**************stdout*****************

catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc ../controlle
rs/home.js"
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc ../controllers/home.js"' }
**************stderr*****************
catdoc: No such file or directory

**************stdout*****************

**Comment by nishvs** [comment]
THere was small mistake in the path.I gave extra .
Now i gave the path "./controllers/home.js"
and i got the following output.

textract: 'drawingtotext' does not appear to be installed, so it will be unable
to extract DXFs.
textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.
Found catdoc, textract should be able to use it.

**Comment by dbashford** [comment]
Ok, so it seems to work whether it is a `.doc` or not.

And it seems to work as long as you provide relative paths.

But when you provide the full path it does not?  Can you try putting in the full path to the file?

**Comment by dbashford** [comment]
O, wait.

When you use `__filename` it was using windows slashes:

`catdoc E:\NewStartup\Code\Tutor
ial\Node Samples\SampleNodeProject\ClientApp\controllers\home.js`

But when you are putting them in by hand, you are using unix slashes.

`./controllers/home.js`

node.js, when it creates `__filename` is going to build an OS specific filename for you.  It is building a windows filename.

**Comment by nishvs** [comment]
so i am putting __filename+'/Resume.doc' in the path line. Is it ok??

**Comment by dbashford** [comment]
It would be `__dirname` not `__filename`, but I think the slashes might be throwing it off.

**Comment by nishvs** [comment]
I gave the path:

exec('catdoc ' + __dirname+'\\Resume.doc' ,

I got the following output 

textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.
textract: 'drawingtotext' does not appear to be installed, so it will be unable
to extract DXFs.
catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc E:\NewStartu
p\Code\Tutorial\Node Samples\SampleNodeProject\ClientApp\controllers\Resume.doc"

catdoc: No such file or directory
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc E:\\NewStartup\\Code\\Tutor
ial\\Node Samples\\SampleNodeProject\\ClientApp\\controllers\\Resume.doc"' }
**************stderr*****************
catdoc: No such file or directory
catdoc: No such file or directory

**************stdout*****************

**Comment by dbashford** [comment]
Something else to try.  Think the slash mismatch is screwing things up.

`var fileName = __filename.replace(/(.+):/, "/$1")`

Then use that `fileName`, so...

`exec('catdoc ' + fileName,`

**Comment by nishvs** [comment]
Sry but i did not understand what you want me to do??

**Comment by dbashford** [comment]
```
#!/usr/bin/env node
var exec = require("child_process").exec;
var fileName = __filename.replace(/(.+):/, "/$1");
exec('catdoc ' + fileName,
  function (error, stdout, stderr) {
    if (error) {
      console.log("catdoc cannot be found/executed by this script, errors to follow.")
      console.log("**************ERROR*****************");
      console.log(error);
      console.log("**************stderr*****************")
      console.log(stderr);
      console.log("**************stdout*****************")
      console.log(stdout);
    } else {
      console.log("Found catdoc, textract should be able to use it.")
    }
  }
);
```

**Comment by nishvs** [comment]
I copied the code above in the method in home.js and ran the application.

I got the following output

textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.
textract: 'drawingtotext' does not appear to be installed, so it will be unable
to extract DXFs.
catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc /E\NewStartu
p\Code\Tutorial\Node Samples\SampleNodeProject\ClientApp\controllers\home.js"
catdoc: No such file or directory
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc /E\\NewStartup\\Code\\Tutor
ial\\Node Samples\\SampleNodeProject\\ClientApp\\controllers\\home.js"' }
**************stderr*****************
catdoc: No such file or directory
catdoc: No such file or directory

**************stdout*****************

**Comment by dbashford** [comment]
i updated the script above, plz try again?

**Comment by nishvs** [comment]
I got the following output:

textract: 'drawingtotext' does not appear to be installed, so it will be unable
to extract DXFs.
textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.
catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc /E\NewStartu
p\Code\Tutorial\Node Samples\SampleNodeProject\ClientApp\controllers\home.js"
catdoc: No such file or directory
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc /E\\NewStartup\\Code\\Tutor
ial\\Node Samples\\SampleNodeProject\\ClientApp\\controllers\\home.js"' }
**************stderr*****************
catdoc: No such file or directory
catdoc: No such file or directory

**************stdout*****************

**Comment by nishvs** [comment]
One minute but what did you update in the script??

**Comment by dbashford** [comment]
I'm hoping you are able to see what I am doing and try to do it yourself.  You are using unix paths for your tests that are working.  Please transform this into a unix path: `/E\NewStartu
p\Code\Tutorial\Node Samples\SampleNodeProject\ClientApp\controllers\home.js`

**Comment by dbashford** [comment]
`/E/NewStartup/Code/Tutorial/Node Samples/SampleNodeProject/ClientApp/controllers/home.js`

**Comment by nishvs** [comment]
K i will do this and same i need to do in the "node_modules/textract/lib/extractors/doc.js" file right??

**Comment by dbashford** [comment]
Just do it in the script to see if that works =)

**Comment by dbashford** [comment]
just hardcode the __full unix path__ to `home.js` and if that works, let me know what that looks like.

**Comment by nishvs** [comment]
Following path i gave: 
var fileName = '/E/NewStartup/Code/Tutorial/Node Samples/SampleNodeProject/ClientApp/controllers/home.js'


Output

textract: 'drawingtotext' does not appear to be installed, so it will be unable
to extract DXFs.
textract: 'catdoc' does not appear to be installed, so it will be unable to extr
act DOCs.
catdoc cannot be found/executed by this script, errors to follow.
**************ERROR*****************
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "catdoc /E/NewStartu
p/Code/Tutorial/Node Samples/SampleNodeProject/ClientApp/controllers/home.js"
catdoc: No such file or directory
catdoc: No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "catdoc /E/NewStartup/Code/Tutorial
/Node Samples/SampleNodeProject/ClientApp/controllers/home.js"' }
**************stderr*****************
catdoc: No such file or directory
catdoc: No such file or directory

**************stdout*****************

**Comment by dbashford** [comment]
You have proven relative paths work.  `./controllers/home.js`.

In order for me to help you I'll need you to figure out how to make a full path work.

What are you using to make Windows unix-y?   GitBash?  Cygwin?

**Comment by nishvs** [comment]
I am sorry but i dont understand your question?? 
i am using normal node.js command prompt...

**Comment by dbashford** [comment]
Let me try to go at this differently.

If you type `catdoc` and nothing else at the command line, what does it output?

**Comment by nishvs** [comment]
I get following output:

Usage:
 catdoc [-vu8btawxlV] [-m number] [-s charset] [-d charset] [ -f format] files

If i provide filepath then it shows the text of the file

**Comment by dbashford** [comment]
I just published a new version of textract, `1.0.1`, please give it a shot?

**Comment by nishvs** [comment]
I am getting the error when i start the project: 

      if (error !== null && error.indexOf( "catdoc: No such file or directory"
                                  ^
TypeError: undefined is not a function
    at E:\NewStartup\Code\Tutorial\Node Samples\SampleNodeProject\ClientApp\node
_modules\textract\lib\extractors\doc.js:48:35
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by dbashford** [comment]
Install `1.0.2`.  Introduced a problem there, should be fixed.

**Comment by nishvs** [comment]
Yes it is working..Thanks for your help i could not have done it without your guidance.Please accept my linked request if it is not much trouble to you. :)

**Comment by nishvs** [comment]
Should i close the issue now..

**Comment by dbashford** [comment]
I took care of it =)

**Comment by dbashford** [comment]
Which invite is you?  Nitish?

**Comment by nishvs** [comment]
Yes i am nitish kumar...
