### ISSUE TITLE
PDF extractor options are ignored

### ISSUE THREAD

**Issue by crazy4groovy** [dbashford/textract#57]
Why does the [pdf extractor ignore](https://github.com/dbashford/textract/blob/master/lib/extractors/pdf.js#L7) the [options](https://www.npmjs.com/package/pdf-text-extract)?

**Comment by dbashford** [comment]
Which options are you interested in?

**Comment by crazy4groovy** [comment]
`-layout` and `-nopgbrk`

**Comment by dbashford** [comment]
The short answer to your question is: "If they were documented well within the node module I may have known to use them."

How do those get passed into the node module?

For instance `nopgbrk` would be a `boolean`?

```javascript
var options = {
  cwd: "./"
}
extract(filePath, options, function (err, pages) {
  if (err) {
    console.dir(err)
    return
  }
  console.dir('extracted pages', pages)
})
```

**Comment by dbashford** [comment]
Quick note, the library has, since the last note here, been updated to include documentation, so I will be allowing options to be passed in with the next release.
