### ISSUE TITLE
[Error: extract docx unzip exec error: Error: stdout maxBuffer exceeded.]

### ISSUE THREAD

**Issue by rodrigogalindez** [dbashford/textract#61]
Hi David, 

I'm getting this error when trying to textract a big .docx file (1.8MB). I tried increasing the maxBuffer setting by doing `$ textract big-file.docx --exec.maxBuffer 512000` but it's not working (tried many values, but none seem to work). 

Do you know a possible fix? 

Thanks!

**Comment by dbashford** [comment]
`1.8MB` may just be too big for the process?  This'll end up being a node process problem more than anything I think.

**Comment by dbashford** [comment]
Closing this out, not sure textract really has much it can do here.
