### ISSUE TITLE
Add CSV support

### ISSUE THREAD

**Issue by sidhuko** [dbashford/textract#62]
We have a requirement for CSV support in a project. Would this be useful to use a popular npm library with the same interface as textract?

I will be able to PR my work early next week.

**Comment by dbashford** [comment]
A CSV is sort of already extracted.  You would just need to treat it like a text file. Right?

**Comment by sidhuko** [comment]
I think the facade you implement is good though to extract from file, url or mime type. You're also extracting one source of file to plain text rather than a sort of extracted file type but I understand your point from theoretical view.

Have need for this is a project so I was considering adding it rather than creating a separate process for the CSV file format. It also is available in the python version so I thought I would ask the question before sending a PR. What do you think?

**Comment by dbashford** [comment]
It should just be one line of code added to the text file extractor.  Just need to add the CSV mime type.

**Comment by dbashford** [comment]
Add CSV mine type here, then add test for it. https://github.com/dbashford/textract/blob/master/lib/extractors/text.js#L14

**Comment by sidhuko** [comment]
Thanks, not much to change to get working for application/csv files. I've setup a docker container for running this on our project, all apart DFX currently, I could integrate this for easier testing and running if you would like?

**Comment by dbashford** [comment]
I'd love to see what that looks like for sure.

**Comment by sidhuko** [comment]
Thanks! I'll open a new ticket as will require some work.
