### ISSUE TITLE
Problems with cyrillic symbols

### ISSUE THREAD

**Issue by TsvetkovAV** [dbashford/textract#65]
When I execute js file with node.js with following content(for example with .doc file):
var textract = require('textract');

textract.fromFileWithPath('test.doc', function( error, text ) {
        if (error) throw error;
	console.log(text);
})

with .doc file, all cyrillic symbols ureadable (but when I execute Catdoc, then I can read it)
and with .docx file all cyrillic symbols removes.

**Comment by dbashford** [comment]
?

**Comment by TsvetkovAV** [comment]
Sorry, pressed 'Ctrl+Enter'

**Comment by dbashford** [comment]
Can you provide or give me an idea of what I should test?  Feel like this problem was solved awhile ago but there may have been a regression.

**Comment by TsvetkovAV** [comment]
Now I found that for both types of files that is the samo problem
All cyrillic characters are removes, displays only latin characters, punctuation symbols and nubers.

**Comment by TsvetkovAV** [comment]
[test.docx](https://github.com/dbashford/textract/files/32219/test.docx)
For example

**Comment by TsvetkovAV** [comment]
If file have only latin characters then 'Textract' work correct, as it can be.
Could you help me with this problem.
I found next:
If I comment next lines:
if ( options.preserveLineBreaks ) {
        // text = text.replace( WHITELIST_PRESERVE_LINEBREAKS, ' ' );
      } else {
        // text = text.replace( WHITELIST_STRIP_LINEBREAKS, ' ' );
      } 
in your code in textract\lib\extract.js,then returns text edition(like paragraphs, spaces) and removed cyrillic characters but as question marks('?'). 
It's  true for file .doc with same text as in test.docx(I attached it in previous comment), but for .docx file is changed only text edition, removed cyrillic characters stay removed.
Thank you.

**Comment by dbashford** [comment]
This should be gtg. Was only happening for `.docx` and for `.odtx` as I had an extra text stripping regex that wasn't updated to include all the non-Latin characters.  

Try `1.2.0`.

**Comment by Ethaan** [comment]
Im having the exact same issue

![screen shot 2016-01-28 at 4 48 04 pm](https://cloud.githubusercontent.com/assets/8289486/12661382/f04773f0-c5de-11e5-85b7-b8b5363b9b83.png)

This is my config.

```
    var  buffer = new Buffer(base64, 'base64'),
          type = 'application/msword',
          config = {
             preserveLineBreaks: true
         };
    textract.fromBufferWithMime(type, buffer, config, function(error, text) {
      if (error) {
        console.log(error);
       return(error);
      } else {
       return(null,text);
      }
    });
```

**NOTE:** This only happend with .doc files im on a MAC also.

**Comment by dbashford** [comment]
Can you give me a sample doc?  (And maybe open a new issue with it to track?)

**Comment by Ethaan** [comment]
Sure.

Here is #71 

Thanks
