### ISSUE TITLE
Disable info text?

### ISSUE THREAD

**Issue by joshterrill** [dbashford/textract#66]
I don't have the DFX conversion software installed so every time I do a text extraction, I get info warning text saying `INFO: 'drawingtotext' does not appear to be installed, so textract will be unable to extract DXFs.` and then the text of my document after it. Is there any way to disable this?

**Comment by dbashford** [comment]
:+1: 

Been thinking about this myself.  Will look into it.

**Comment by dbashford** [comment]
Those pesky messages should be gone.  Now textract will wait until you attempt to extract something it is incapable of extracting before telling you that initialization for that type failed.

**Comment by dbashford** [comment]
Published with `1.2.0`
