### ISSUE TITLE
lang parameter

### ISSUE THREAD

**Issue by appinteractive** [dbashford/textract#67]
How do I pass the language that should be used for ocr?

**Comment by dbashford** [comment]
https://github.com/dbashford/textract#configuration

> tesseract.lang: A pass-through to tesseract allowing for setting of language for extraction. ex: { tesseract: { lang:"chi_sim" } }

**Comment by appinteractive** [comment]
Could you please give me an complete example? What is a pass-through and how do I use it on the command line?

I tried the following (non was working)
- textract scan.jpg --exct "{ tesseract: { lang:'deu' } }"
- textract scan.jpg --exec.tesseract.lang "{ tesseract: { lang:'deu' } }"
- textract scan.jpg exec="{ tesseract: { lang:'deu' } }"
- textract scan.jpg "{ tesseract: { lang:'deu' } }"
- textract scan.jpg ex: "{ tesseract: { lang:'deu' } }"

**Comment by dbashford** [comment]
--tesseract.lang=deu

Give that a try?

**Comment by appinteractive** [comment]
ahh thank you very much! maybe you could add an concrete example to the readme to make this more clear. :)
