### ISSUE TITLE
.docx keep font size, type and color.

### ISSUE THREAD

**Issue by Ethaan** [dbashford/textract#70]
Its there a way to keep the font size and other things of a .docx document?

right now i have something like this.

```javascript
Meteor.methods({
  'GET/DocxText': function(base64) {
    check([base64], [String]);
    var textractFuture = new future(),
      buffer = new Buffer(base64, 'base64'),
      type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      config = {
        preserveLineBreaks: true
      };
    textract.fromBufferWithMime(type, buffer, config, function(error, text) {
      if (error) {
        console.log(error);
        textractFuture.return(error);
      } else {
        console.log(text);
        textractFuture.return(text);
      }
    });
    return textractFuture.wait();
  }
});
```
But its there a way to keep the standar markup?

Thanks!

**Comment by dbashford** [comment]
That is pretty soundly outside the scope of textract. The goal with it is to just pull out the text.  Attempting to pull out more than that would not only be really difficult, but also a slippery slope since all the various document formats will present formatting in different ways.
