### ISSUE TITLE
Remove cyrillic symbols from a .doc file.

### ISSUE THREAD

**Issue by Ethaan** [dbashford/textract#71]
This is the file im using

[sample.doc](https://files.zenhub.io/56ab6ea512189dca2c5ee268)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

And this is how im doing it.

On the client side i have a simple.

Im reading the file using the File Reader API, and then passing to the server a base64 string. like this.
`var base64 = data.target.result.replace(/^data:application\/(vnd.openxmlformats-officedocument.wordprocessingml.document);base64,/, "");`

Then on the server, im doing this.

```
buffer = new Buffer(base64, 'base64')
type = 'application/msword';
config = {
        preserveLineBreaks: true
    };

textract.fromBufferWithMime(type, buffer, config, function(error, text) {
      if (error) {
        console.log(error);
      } else {
        console.log(text)
      }
    });
```

This works great for .docx files, but with .doc files im getting something like this

![f04773f0-c5de-11e5-85b7-b8b5363b9b83](https://cloud.githubusercontent.com/assets/8289486/12677367/11e2ad16-c65e-11e5-8f83-23e15c25ac1c.png)

*UPDATE* doing a `fromUrl` works great, so maybe the problem its the way im passing the buffer to the method `fromBufferWithMime`?

**Comment by dbashford** [comment]
I've plugged that file in and don't seem to be having any issues.  All of the cyrillic you are seeing at the top of the screenshot, that is being output by textract and you are not expecting it?

Given the `fromUrl` was working, closing this as in the end that uses the same code path. If you've got more details, toss them in here and I can reopen.  Thanks!
