### ISSUE TITLE
application/pdf type not found

### ISSUE THREAD

**Issue by SamVerschueren** [dbashford/textract#73]
This is the error I receive when using `textract`.

> { [Error: Error for type: [[ application/pdf ]], file: [[ test.pdf ]]] typeNotFound: true }

This is the piece of code I use

```js
m(html).then(buffer => {
	fs.writeFileSync('test.pdf', buffer);

	textract.fromFileWithPath('test.pdf', function (err, result) {
		if (err) {
			console.log(err);
		} else {
			console.log(result);
		}

		t.end();
	});
});
```

I tried `textract` with the mime type and the buffer directly, no dice, same error.

I use Docker and installed all the extra packages

```
$ apt-get install -y poppler-utils catdoc xpdf tesseract-ocr
```

Something I'm missing here?

**Comment by dbashford** [comment]
> PDF extraction requires pdftotext be installed

Have that?

**Comment by SamVerschueren** [comment]
Aha, I was too soon. Managed to get it working on `travis-ci`. `xpdf` wasn't properly installed. My bad :).

**Comment by dbashford** [comment]
:+1:
