### ISSUE TITLE
Support application/vnd.ms-excel.sheet.binary.macroenabled.12

### ISSUE THREAD

**Issue by titarenko** [dbashford/textract#78]
Hi,

Thanks for great project!

Could you add support for `application/vnd.ms-excel.sheet.binary.macroenabled.12`?

Currently (version `1.2.1`) extraction ends with:

```js
textract.fromFileWithPath('18.xlsb', console.log);
```
```
{ [Error: Error for type: [[ application/vnd.ms-excel.sheet.binary.macroenabled.12 ]], file: [[ 18.xlsb ]]] typeNotFound: true } null
```

**Comment by dbashford** [comment]
Looks like a casing problem (`macroenabled ` vs `macroEnabled `) as textract does have support for this.  Should be a quick fix.  Want to get this into 1.3, though.  Been bogged down by work and sick kids lately but need to push through to get that out.
