### ISSUE TITLE
Issue with cheerio 0.19.0

### ISSUE THREAD

**Issue by jbilcke** [dbashford/textract#82]
Hi,

There is an issue when parsing markdown: content gets translated to HTML, 
but Cheerio then fails to parse it:

```javascript
  ...
  text = "<textractwrapper>" + text + "<textractwrapper>";
  try {
    $ = cheerio.load( text );
    $('script').remove(); // <<< this line crashes with message:   TypeError: Cannot read property 'children' of undefined
  ...
```

This is caused by a regression in cheerio 0.19.0:

https://github.com/cheeriojs/cheerio/issues/804

I would advise to upgrade to cheerio 0.20.0, which works fine

**Comment by dbashford** [comment]
Closed by PR
