### ISSUE TITLE
npm3's flat node_modules structure causes 'not found' error when extracting text from Excel 

### ISSUE THREAD

**Issue by PraneethVT** [dbashford/textract#91]
Hey, for your Textract module, there is a bug now because of the new Nodev6.2.2 when extracting text from Excel. 

Error: Could not extract usearch-1466710851433.xlsx, Command failed: /home/praneeth/Upward/uapi/node_modules/textract/node_modules/j/bin/j.njs ./test/tmp/xlsx/usearch-1466710851433.xlsx
/bin/sh: 1: /home/praneeth/Upward/uapi/node_modules/textract/node_modules/j/bin/j.njs: not found

Because of Nodev6's flat node_modules structure now, the "j" library cannot be found, it's now located in the same node_module folder as "textract" and everything else.

**Comment by dbashford** [comment]
There is a PR that addresses this.  Will be furthering along towards 2.0 this weekend.  Expecting to release weekend of the 4th.

**Comment by dbashford** [comment]
This is resolved with https://github.com/dbashford/textract/pull/89, just needs release. Hopefully sometime later this week or during the long weekend.
