### ISSUE TITLE
Older Word docs evoking extraction errors

### ISSUE THREAD

**Issue by tysun** [dbashford/textract#94]
Hi David

Do you know if there is an issue with the underlying Antiword reader that textract uses?

Wiki says Antiword can convert the documents from Microsoft Word version 2, 6, 7, 97, 2000, 2002 and 2003 to plain text.

However, for us, extraction from docs other than docx gives this error:
[Error: file named [[ 187292 ]] does not appear to really be a .doc file]

We are pulling PDF and 2003 Word docs online and extracting on a Node/ubuntu and sending back text to iOS. PDF and docx working fine.

Thanks

**Comment by dbashford** [comment]
Hoping to get some time in the next few weeks to knock out the next batch of tickets. Will take a look at this. May be a case where we need to trust the mine type being passed in. I'm guessing you are feeding in a mine type?

**Comment by tysun** [comment]
Hi,

Thanks for replying.

We've tried passing in a mime type (i.e. telling textract that it is a Word doc) and it doesn’t make a difference. But interestingly, the unix ‘file' utility correctly detects that it is a Word doc: https://en.wikipedia.org/wiki/File_(command)

**Comment by dbashford** [comment]
So, few things, I can see a problem in the code:  https://github.com/dbashford/textract/blob/48df3ccfce3552cdd903768c649cf1a74d991015/lib/extractors/doc.js#L14

If you go into node_modules and change that to check for `> 0`, then you'll likely fix that check.  However, the fact that it got in there means antiword errored out. It may well be another error in textract causing that though.

**Comment by andre0799** [comment]
+1

**Comment by dbashford** [comment]
Anyone have an example `.doc`?

**Comment by dbashford** [comment]
@andre0799 @tysun I have addressed some bad error handling in the code with version `2.1`. If you try again, I wonder if the error you get might be more enlightening?

Let me know!

**Comment by dbashford** [comment]
Closing, old, if still a problem and an example doc can be provided, let me know and I'll dig in.
