### ISSUE TITLE
extract text from url 

### ISSUE THREAD

**Issue by veljkomatic** [dbashford/textract#97]
Hi, 
First to thank you for awesome library. My problem is url encoding, my url contains special character ', and somewhere in lib it encoding url and replace  special character  '  with %27 and it fucked up url. Can you help me, is there some config parameter?

Thanks a lot 
Veljko

**Comment by dbashford** [comment]
textract uses got [got](https://github.com/sindresorhus/got) to execute the request to fetch the file.  And it [doesn't manipulate the file path at all](https://github.com/dbashford/textract/blob/a8923704a35c15bc88fd45eecf4470506b87a32c/lib/index.js#L118-L132) before executing the `got` request.

Don't have time to look now, but the question would be, does `got` support anything that would prevent the encoding?  If so, I can expose that via an option.

**Comment by veljkomatic** [comment]
Thanks a lot for answer. Yes that is the question. 
got does encoding, and change  ' to %27. 

I will be thankful, if you add option for that.

Thank a lot!
Veljko

**Comment by dbashford** [comment]
This has been published with textract `2.1`, sorry for the delay!
