### ISSUE TITLE
cannot extract Chinese comma symbol

### ISSUE THREAD

**Issue by lcc19941214** [dbashford/textract#99]
I'm using textract and it's awesome! I can easily extract content from any of my .doc or .docx files.

However, most of my time I'm handling with documents full of Chinese characters and it seems like textract has some porblem with extracting Chinese comma symbol '，' (with space instead).

**Comment by dbashford** [comment]
👍 

I tend to update textract every 3 months or so and I am overdue. Hoping to be taking a good look at all the various issues/PRs this time next week.

**Comment by dbashford** [comment]
@lcc19941214 Not an issue anymore?

The last time I spent time working textract stuff I was working this. Didn't check anything in but believe I was close to resolving this.

**Comment by dbashford** [comment]
FWIW, the fix for this was just published as textract `2.1`, thanks!
